set(_CATKIN_CURRENT_PACKAGE "project_pkg")
set(project_pkg_VERSION "0.0.0")
set(project_pkg_MAINTAINER "ecn <ecn@todo.todo>")
set(project_pkg_PACKAGE_FORMAT "2")
set(project_pkg_BUILD_DEPENDS )
set(project_pkg_BUILD_EXPORT_DEPENDS )
set(project_pkg_BUILDTOOL_DEPENDS "catkin")
set(project_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(project_pkg_EXEC_DEPENDS )
set(project_pkg_RUN_DEPENDS )
set(project_pkg_TEST_DEPENDS )
set(project_pkg_DOC_DEPENDS )
set(project_pkg_URL_WEBSITE "")
set(project_pkg_URL_BUGTRACKER "")
set(project_pkg_URL_REPOSITORY "")
set(project_pkg_DEPRECATED "")